spring:
  profiles:
    active: dev
  application:
    name: jiuhubao-api
  mvc:
    # 处理404，不直接返回页面
    throw-exception-if-no-handler-found: true
  resources:
    # 是否开启资源映射
    add-mappings: false
  main:
    # 配置banner显示
    banner-mode: console
  http:
    encoding:
      charset: UTF-8
  # jackson时间格式化
  jackson:
    # 时区
    time-zone: GMT+8
    # 时间格式
    date-format: yyyy-MM-dd HH:mm:ss
############################################
## 服务器基本配置
############################################
server:
  # 连接超时配置
  connection-timeout: 30000
  # 路径配置
  servlet:
    context-path: /api
  tomcat:
    uri-encoding: UTF-8
    max-threads: 2000
    min-spare-threads: 20
redis:
  timeout: 3000
#打开feign-hystrix
feign:
  hystrix:
    enabled: true
ribbon:
  #对所有操作请求都进行重试,默认false
  OkToRetryOnAllOperations: false
  #负载均衡超时时间，默认值5000
  ReadTimeout: 3000
  #ribbon请求连接的超时时间，不包括首次调用，默认值2000
  ConnectTimeout: 2000
  #对当前实例的重试次数，默认0
  MaxAutoRetries: 1
  #对切换实例的重试次数，默认1
  MaxAutoRetriesNextServer: 1
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000
            
---

eureka:
  server:
    host: 127.0.0.1
    port: 8080
  # 注册服务中心用户名及密码
  security:
    username: jiuhubao
    password: password
  # 注册服务中心配置
  client:
    serviceUrl:
      defaultZone: http://${eureka.security.username}:${eureka.security.password}@${eureka.server.host}:${eureka.server.port}/eureka
spring:
  profiles: dev
  datasource:
    core:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.22.70.2:3306/jiuhu_core?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
      username: ogemray
      password: ajr@123
  redis:
    # Redis服务器连接地址
    host: 10.22.70.115
    # Redis服务器连接端口
    port: 6379
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码
    password:
jwt:
  #jwt 服务端密钥
  secret: aml1aHUtYXBpLXYx
  #jwt 过期时间,0为永久有效,单位:分钟
  expiration: 0
push:
  host: 10.22.70.19
  port: 8084
  name: ws
  remote-path: http://${push.host}:8083/socket
    
---

eureka:
  server:
    host: 47.112.208.167
    port: 9000
  # 注册服务中心用户名及密码
  security:
    username: jiuhubao
    password: password
  # 注册服务中心配置
  client:
    serviceUrl:
      defaultZone: http://${eureka.security.username}:${eureka.security.password}@${eureka.server.host}:${eureka.server.port}/eureka
spring:
  profiles: test
  datasource:
    core:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-wz911qjz60xy2rzae.mysql.rds.aliyuncs.com:3306/jiuhu_core_test?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
      username: root
      password: jiuhubao@123
  redis:
    # Redis服务器连接地址
    host: r-wz93eb5ae5c6db24.redis.rds.aliyuncs.com
    # Redis服务器连接端口
    port: 6379
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码
    password: jiuhu@123
jwt:
  #jwt 服务端密钥
  secret: aml1aHUtYXBpLXYx
  #jwt 过期时间,0为永久有效,单位:分钟
  expiration: 2592000
push:
  host: 47.112.208.167
  port: 9004
  name: ws
  remote-path: http://${push.host}:9003/socket

---

eureka:
  server:
    host: 47.112.208.167
    port: 9000
  # 注册服务中心用户名及密码
  security:
    username: jiuhubao
    password: password
  # 注册服务中心配置
  client:
    serviceUrl:
      defaultZone: http://${eureka.security.username}:${eureka.security.password}@${eureka.server.host}:${eureka.server.port}/eureka
spring:
  profiles: pro
  datasource:
    core:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-wz911qjz60xy2rzae.mysql.rds.aliyuncs.com:3306/jiuhu_core_test?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
      username: root
      password: jiuhubao@123
  redis:
    # Redis服务器连接地址
    host: r-wz93eb5ae5c6db24.redis.rds.aliyuncs.com
    # Redis服务器连接端口
    port: 6379
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码
    password: jiuhu@123
jwt:
  #jwt 服务端密钥
  secret: aml1aHUtYXBpLXYx
  #jwt 过期时间,0为永久有效,单位:分钟
  expiration: 2592000
push:
  host: 47.112.208.167
  port: 9004
  name: ws
  remote-path: http://${push.host}:9003/socket
