spring:
  profiles: test
    active: test

---

server:
  port: 9022
spring:
  profiles: dev
  application:
    name: test-cloud-dev-2.0

---

spring:
  profiles: test
  application:
    name: test-cloud-test-2.0
